name: Build on push

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target: [aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        name: Install arm gcc
        run: sudo apt install gcc-aarch64-linux-gnu
      - name: Setup target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: comet-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/comet
