name: Build on push

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup target
        run: rustup target add ${{ matrix.target }}
      - run: sudo dpkg --add-architecture arm64 && sudo apt-get update
        continue-on-error: true
      - if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: sudo apt-get install gcc-aarch64-linux-gnu libssl-dev:arm64
      - name: Setup dependencies
        run: sudo apt-get install libssl-dev
      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: comet-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/comet
