name: Lint

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Check formatting
        run: cargo fmt --check -v
      - name: Clippy
        run: cargo clippy -all-targets --all-features
